name: Ensure PR is up to date with target branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the PR branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch target branch (e.g., main)
      run: git fetch origin ${{ github.base_ref }}

    - name: Check if PR branch is up-to-date with target branch
      run: |
        # Get the latest commit on the PR branch and target branch
        PR_HEAD=$(git rev-parse HEAD)
        TARGET_HEAD=$(git rev-parse origin/${{ github.base_ref }})

        # Compare the two
        if [ "$PR_HEAD" != "$TARGET_HEAD" ]; then
          echo "PR is not up-to-date with the latest target branch."
          exit 1
        else
          echo "PR is up-to-date."
        fi